version: "3"
services:
  api:
    build: ./api
    env_file: ./common.env
    volumes:
      - ./api:/src
    depends_on:
      - postgres
    command: ["npm", "start"]
  postgres:
    image: postgres:10.5
    env_file: ./common.env
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/src
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: 3000
    command: ["npm", "run", "dev"]
