version: "3"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/src
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: 3000
    command: ["npm", "run", "dev"]
